# Disable LGTM's built-in query to detect unsafe uses of gmtime; there's a
# custom query to check for that
queries:
  - exclude: cpp/potentially-dangerous-function

extraction:
  cpp:
    after_prepare:
      - echo 'deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_18.10 ./' | tee  /etc/apt/sources.list.d/syslog-ng-obs.list
      - apt-get update -qq

