# Disable LGTM's built-in query to detect unsafe uses of gmtime; there's a
# custom query to check for that
queries:
  - exclude: cpp/potentially-dangerous-function

extraction:
  cpp:
    prepare:
      packages:
        - autoconf-archive
        - bison
        - docbook-xsl
        - flex
        - gradle
        - libcap-dev
        - libdbd-sqlite3
        - libdbi0-dev
        - libesmtp-dev
        - libgeoip-dev
        - libglib2.0-dev
        - libhiredis-dev
        - libivykis-dev
        - librabbitmq-dev
        - libmongoc-dev
        - libjson0-dev
        - libnet1-dev
        - libriemann-client-dev
        - librdkafka-dev
        - libwrap0-dev
        - pkg-config
        - sqlite3
        - xsltproc
        - criterion-dev
        - libmaxminddb-dev
        - libxml2-utils
        - doxygen
        - libsnmp-dev

    configure:
      command:
        - ./autogen.sh
        - ./configure --disable-java


