# Disable LGTM's built-in query to detect unsafe uses of gmtime; there's a
# custom query to check for that
queries:
  - exclude: cpp/potentially-dangerous-function

extraction:
  cpp:
    prepare:
      packages:
        - bison
        - cmake
        - docbook-xsl
        - doxygen
        - flex
        - libcap-dev
        - libcurl4-openssl-dev
        - libdbd-sqlite3
        - libdbi0-dev
        - libesmtp-dev
        - libgeoip-dev
        - libglib2.0-dev
        - libhiredis-dev
        - libivykis-dev
        - libjson-c-dev
        - libmaxminddb-dev
        - libnet1-dev
        - librabbitmq-dev
        - librdkafka-dev
        - libriemann-client-dev
        - libsnmp-dev
        - libwrap0-dev
        - libxml2-utils
        - python-dev
        - python-pip
        - python-setuptools
        - pkg-config
        - sqlite3
        - xsltproc
    configure:
      command:
        - cmake . -Bbuild -DIVYKIS_SOURCE=system -DJSONC_SOURCE=system -DSYSLOG_NG_ENABLE_DEBUG=ON -DENABLE_JAVA=OFF -DENABLE_MONGODB=OFF
