language: c
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo bash .bootstrap/travis_install_ubuntu.sh; fi
before_script:
  - ./autogen.sh
script:
  - ./configure --with-ivykis=internal --prefix=$HOME/install/syslog-ng --enable-pacct
  - make
  - make distcheck VERBOSE=1
  - make func-test VERBOSE=1
compiler:
  - gcc
  - clang
branches:
  except:
    - /wip/
notifications:
  irc:
    channels:
      - "irc.freenode.org#balabit"
